// app actions


// pones actions
export const FETCH_PHONES_START = 'PHONE/FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'PHONE/FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAILED = 'PHONE/FETCH_PHONES_FAILED';

// phone actions
export const FETCH_PHONE_START = 'PHONE/FETCH_PHONE_START';
export const FETCH_PHONE_SUCCESS = 'PHONE/FETCH_PHONE_SUCCESS';
export const FETCH_PHONE_FAILED = 'PHONE/FETCH_PHONE_FAILED';

// load more phones
export const LOAD_MORE_PHONES_START = 'PHONES_PAGE/LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'PHONES_PAGE/LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_FAILED = 'PHONES_PAGE/LOAD_MORE_PHONES_FAILED';3

// basket actions
export const ADD_PHONE_TO_BASKET = 'BASKET/ADD_PHONE_TO_BASKET';
